# Generated by Django 4.1.3 on 2023-02-15 19:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyInput',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('type', models.CharField(choices=[('i', 'داخلي'), ('o', 'خارجي')], max_length=255, verbose_name='داخلي او خارجي')),
                ('address', models.CharField(max_length=255, verbose_name='الموقع')),
                ('officeName', models.CharField(max_length=255, verbose_name='اسم المكتب')),
                ('itemType', models.CharField(max_length=255, verbose_name='نوع المنتج')),
                ('itemName', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('oneItemPrice', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='سعر المفرد')),
                ('marketPrice', models.CharField(max_length=500, verbose_name='سعر المفرد في الاسواق')),
                ('myPrice', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='سعرنا')),
                ('numberOfItem', models.IntegerField(verbose_name='العدد')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاريخ ووقت الاضافة')),
                ('notes', models.JSONField(blank=True, null=True, verbose_name='ملاحظات')),
                ('itemImage', models.ImageField(blank=True, null=True, upload_to='images/item', verbose_name='صورة المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('i', 'داخلي'), ('o', 'خارجي')], max_length=255, verbose_name='داخلي او خارجي')),
            ],
        ),
        migrations.CreateModel(
            name='SalesAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المشتري')),
                ('place', models.CharField(max_length=255, verbose_name='العنوان')),
                ('phoneNumber', models.CharField(max_length=255, verbose_name='رقم الهاتف')),
                ('notes', models.JSONField(blank=True, null=True, verbose_name='ملاحظات')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='التاريخ')),
                ('delivary', models.BooleanField(default=False)),
                ('finish', models.BooleanField(default=False)),
                ('delivaryPrice', models.IntegerField(blank=True, default=0, null=True, verbose_name='سعر التوصيل')),
            ],
        ),
        migrations.CreateModel(
            name='SourceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('placeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeName', to='pharmacy.placename')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('notes', models.CharField(blank=True, max_length=700, null=True)),
                ('unitPrice', models.IntegerField(verbose_name='سعر الشراء')),
                ('numberOfItem', models.IntegerField(verbose_name='العدد')),
                ('ItemPrice', models.IntegerField(verbose_name='سعر المفرد')),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyName', to='pharmacy.companyname')),
                ('itemName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemName', to='pharmacy.itemname')),
                ('salesItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesItems', to='pharmacy.salesaccount', verbose_name='المواد')),
                ('sourceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceName', to='pharmacy.sourcename')),
            ],
        ),
    ]
