# Generated by Django 4.1.3 on 2023-02-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_advertisment_advertismentname_delete_pharmacyinput_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAccountName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='salesaccount',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='pharmacy.placeaccountname', verbose_name='العنوان'),
        ),
    ]
