# Generated by Django 4.1.7 on 2023-04-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_salesaccount_delivarydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesaccount',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='رابط'),
        ),
        migrations.AlterField(
            model_name='salesaccount',
            name='date',
            field=models.DateTimeField(verbose_name='التاريخ'),
        ),
    ]
