# Generated by Django 4.1.7 on 2023-07-15 16:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_salesaccount_link_alter_salesaccount_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المشتري')),
                ('phoneNumber', models.CharField(max_length=11, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('unitPrice', models.IntegerField(verbose_name='سعر الشراء')),
                ('numberOfItem', models.IntegerField(verbose_name='العدد')),
                ('ItemPrice', models.IntegerField(verbose_name='سعر المفرد')),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='pharmacy.companyname')),
                ('itemName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='pharmacy.itemname')),
                ('sourceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='pharmacy.sourcename')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingBill',
            fields=[
                ('requestDate', models.DateTimeField(auto_created=True, verbose_name='تاريخ الطلب')),
                ('billNumber', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('delivary', models.BooleanField(default=False)),
                ('deliveryPrice', models.IntegerField(blank=True, default=0, null=True, verbose_name='سعر التوصيل')),
                ('confirmation', models.BooleanField(default=False)),
                ('confirmationDate', models.DateTimeField(verbose_name='تاريخ تاكيد الطلب')),
                ('delivered', models.BooleanField(default=False)),
                ('delivaryDate', models.DateTimeField(verbose_name='تاريخ التوصيل')),
                ('customerInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerInformation', to='pharmacy.customerinformation')),
                ('shoppingItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingItem', to='pharmacy.shoppingitem')),
            ],
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountPlace', to='pharmacy.customerlocation', verbose_name='العنوان'),
        ),
    ]
