# Generated by Django 4.1.7 on 2023-07-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_customerinformation_customerlocation_shoppingitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlocation',
            name='name',
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='governorate',
            field=models.CharField(choices=[('الأنبار', 'الأنبار'), ('البصرة', 'البصرة'), ('بابل', 'بابل'), ('بغداد', 'بغداد'), ('دهوك', 'دهوك'), ('ديالى', 'ديالى'), ('ذي قار', 'ذي قار'), ('صلاح الدين', 'صلاح الدين'), ('كربلاء', 'كربلاء'), ('كركوك', 'كركوك'), ('ميسان', 'ميسان'), ('النجف', 'النجف'), ('نينوى', 'نينوى'), ('واسط', 'واسط')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='nearby',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerlocation',
            name='zone',
            field=models.CharField(default='g', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingbill',
            name='requestDate',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='تاريخ الطلب'),
        ),
    ]
