# Generated by Django 4.1.7 on 2023-07-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_remove_customerlocation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlocation',
            name='governorate',
            field=models.CharField(choices=[('الأنبار', 'الأنبار'), ('البصرة', 'البصرة'), ('بابل', 'بابل'), ('بغداد', 'بغداد'), ('دهوك', 'دهوك'), ('ديالى', 'ديالى'), ('ذي قار', 'ذي قار'), ('صلاح الدين', 'صلاح الدين'), ('كربلاء', 'كربلاء'), ('كركوك', 'كركوك'), ('ميسان', 'ميسان'), ('النجف', 'النجف'), ('نينوى', 'نينوى'), ('واسط', 'واسط')], max_length=50, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='customerlocation',
            name='nearby',
            field=models.CharField(max_length=255, verbose_name='اقرب نقطة دالة'),
        ),
        migrations.AlterField(
            model_name='customerlocation',
            name='zone',
            field=models.CharField(max_length=255, verbose_name='المنطقة'),
        ),
    ]
