# Generated by Django 4.1.7 on 2023-07-15 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_customerlocation_governorate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='المنطقة')),
            ],
        ),
        migrations.AlterField(
            model_name='customerlocation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='pharmacy.zone', verbose_name='المنطقة'),
        ),
    ]
