# Generated by Django 4.1.7 on 2023-07-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_zone_alter_customerlocation_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingbill',
            name='confirmationDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تاكيد الطلب'),
        ),
        migrations.AlterField(
            model_name='shoppingbill',
            name='delivaryDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوصيل'),
        ),
    ]
