# Generated by Django 4.1.7 on 2023-07-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_alter_shoppingbill_confirmationdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingbill',
            name='shoppingItem',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingItem', to='pharmacy.shoppingbill'),
            preserve_default=False,
        ),
    ]
