# Generated by Django 4.1.7 on 2023-07-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_itemimage_remove_shoppingitem_itemprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(default=54641345123413, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='pharmacy.item'),
            preserve_default=False,
        ),
    ]
