# Generated by Django 4.1.7 on 2023-07-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_alter_itemimage_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingbill',
            name='item',
        ),
    ]
