# Generated by Django 4.1.7 on 2023-07-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0017_alter_shoppingbill_billnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbill',
            name='item',
            field=models.ManyToManyField(related_name='items', to='pharmacy.item'),
        ),
        migrations.AlterField(
            model_name='shoppingbill',
            name='billNumber',
            field=models.CharField(auto_created=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
