# Generated by Django 4.1.7 on 2023-07-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0018_shoppingbill_item_alter_shoppingbill_billnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='unitPrice',
            new_name='sourcePrice',
        ),
        migrations.AddField(
            model_name='item',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesaccount',
            name='id',
            field=models.CharField(auto_created=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
