# Generated by Django 4.1.7 on 2023-07-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0019_rename_unitprice_item_sourceprice_item_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlocation',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='item',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sourceName',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='shoppingbill',
            name='customerInformation',
        ),
        migrations.RemoveField(
            model_name='shoppingbill',
            name='item',
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='bill',
        ),
        migrations.DeleteModel(
            name='CustomerInformation',
        ),
        migrations.DeleteModel(
            name='CustomerLocation',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
        migrations.DeleteModel(
            name='ShoppingBill',
        ),
        migrations.DeleteModel(
            name='ShoppingItem',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
