# Generated by Django 4.1.7 on 2023-08-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0021_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='details',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
