# Generated by Django 4.1.7 on 2023-08-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0022_item_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
