# Generated by Django 4.1.7 on 2023-08-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0024_alter_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisment',
            new_name='Outcome',
        ),
        migrations.RenameModel(
            old_name='AdvertismentName',
            new_name='OutcomeName',
        ),
    ]
