# Generated by Django 4.1.7 on 2023-08-11 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0025_rename_advertisment_outcome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المشتري')),
                ('phoneNumber', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('accountLink', models.TextField(blank=True, null=True, verbose_name='رابط')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('sourcePrice', models.IntegerField(verbose_name='سعر الشراء')),
                ('numberOfItem', models.IntegerField(verbose_name='العدد')),
                ('ItemPrice', models.IntegerField(verbose_name='سعر المفرد')),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='pharmacy.companyname')),
                ('itemName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='pharmacy.itemname')),
                ('sourceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='pharmacy.sourcename')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('name', models.CharField(max_length=255, verbose_name='المنطقة')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingBill',
            fields=[
                ('requestDate', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='تاريخ الطلب')),
                ('billNumber', models.CharField(auto_created=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('delivary', models.BooleanField(default=False)),
                ('deliveryPrice', models.IntegerField(blank=True, default=0, null=True, verbose_name='سعر التوصيل')),
                ('delivered', models.BooleanField(default=False)),
                ('delivaryDate', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوصيل')),
                ('customerInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerInformation', to='pharmacy.customerinformation')),
                ('item', models.ManyToManyField(related_name='items', to='pharmacy.item')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLocation',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('governorate', models.CharField(choices=[('الأنبار', 'الأنبار'), ('البصرة', 'البصرة'), ('بابل', 'بابل'), ('بغداد', 'بغداد'), ('دهوك', 'دهوك'), ('ديالى', 'ديالى'), ('ذي قار', 'ذي قار'), ('صلاح الدين', 'صلاح الدين'), ('كربلاء', 'كربلاء'), ('كركوك', 'كركوك'), ('ميسان', 'ميسان'), ('النجف', 'النجف'), ('نينوى', 'نينوى'), ('واسط', 'واسط')], max_length=50, verbose_name='المحافظة')),
                ('nearby', models.CharField(max_length=255, verbose_name='اقرب نقطة دالة')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='pharmacy.zone', verbose_name='المنطقة')),
            ],
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountPlace', to='pharmacy.customerlocation', verbose_name='العنوان'),
        ),
    ]
