# Generated by Django 4.1.7 on 2023-08-11 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0026_customerinformation_item_zone_shoppingbill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinformation',
            name='accountLink',
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='location',
        ),
        migrations.AddField(
            model_name='shoppingbill',
            name='accountLink',
            field=models.TextField(blank=True, null=True, verbose_name='رابط'),
        ),
        migrations.AddField(
            model_name='shoppingbill',
            name='location',
            field=models.ForeignKey(default='01f7b61f-3893-4098-8041-a3b0c0f87073', on_delete=django.db.models.deletion.CASCADE, related_name='accountPlace', to='pharmacy.customerlocation', verbose_name='العنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerlocation',
            name='nearby',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اقرب نقطة دالة'),
        ),
        migrations.AlterField(
            model_name='customerlocation',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='pharmacy.zone', verbose_name='المنطقة'),
        ),
    ]
