# Generated by Django 4.1.7 on 2023-08-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0028_governorate_alter_customerlocation_governorate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ItemPrice',
            new_name='itemPrice',
        ),
    ]
