# Generated by Django 4.1.7 on 2023-08-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0029_rename_itemprice_item_itemprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinformation',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='shoppingbill',
            name='phoneNumber',
            field=models.CharField(default=' ', max_length=50, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingbill',
            name='requestDate',
            field=models.DateTimeField(verbose_name='تاريخ الطلب'),
        ),
    ]
