# Generated by Django 4.1.7 on 2023-08-18 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0030_remove_customerinformation_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCompanyName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewItemName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewNumberOfItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('number', models.IntegerField(verbose_name='العدد')),
            ],
        ),
        migrations.CreateModel(
            name='NewPlaceName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('i', 'داخلي'), ('o', 'خارجي')], max_length=255, verbose_name='داخلي او خارجي')),
            ],
        ),
        migrations.CreateModel(
            name='NewPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('price', models.IntegerField(verbose_name='سعر الشراء')),
            ],
        ),
        migrations.CreateModel(
            name='NewSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي'),
        ),
        migrations.CreateModel(
            name='NewSourceName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('name', models.CharField(max_length=255)),
                ('placeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeName', to='pharmacy.newplacename')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='companyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='pharmacy.newcompanyname'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='pharmacy.newitemname'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemPrice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemPrice', to='pharmacy.newprice'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numberOfItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numberOfItem', to='pharmacy.newnumberofitem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemSize', to='pharmacy.newsize'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sourceName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='pharmacy.newsourcename'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sourcePrice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcePrice', to='pharmacy.newprice'),
        ),
    ]
