# Generated by Django 4.1.7 on 2023-08-11 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0030_remove_customerinformation_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCompanyName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewItemName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewPlaceName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('i', 'داخلي'), ('o', 'خارجي')], max_length=255, verbose_name='داخلي او خارجي')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي'),
        ),
        migrations.CreateModel(
            name='NewSourceName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='الرمز التسلسلي')),
                ('name', models.CharField(max_length=255)),
                ('placeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeName', to='pharmacy.newplacename')),
            ],
        ),
    ]
