# Generated by Django 4.1.7 on 2023-08-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0031_newcompanyname_newitemname_newplacename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='companyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='pharmacy.newcompanyname'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='pharmacy.newitemname'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sourceName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='pharmacy.newsourcename'),
        ),
    ]
